name: Build TrollFools

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download dylib
      run: |
        curl -L "https://drive.google.com/uc?export=download&id=17az2NmgbT6YusYsMpd32wyioi4MV_BrY" -o TrollFools/File.dylib

    - name: Build project
      run: |
        xcodebuild -project TrollFools.xcodeproj \
          -scheme TrollFools \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

    - name: Create IPA
      run: |
        mkdir Payload
        cp -r build/Build/Products/Release-iphoneos/TrollFools.app Payload/
        zip -r TrollFools.ipa Payload
